In [ ]:
# Import required libraries
import pandas as pd
import numpy as np

# Load the Titanic dataset
df = pd.read_csv("data/train.csv")

# Display the first 5 rows
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
# Check the number of rows and columns
print("Shape:", df.shape)

# Display column names
print("\nColumns:")
print(df.columns)

# Show data types and missing values
print("\nDataset Information:")
df.info()

# Count missing values in each column
print("\nMissing Values:")
print(df.isnull().sum())

# Display summary statistics for numeric columns
print("\nSummary Statistics:")
display(df.describe())

Shape: (891, 12)

Columns:
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

Missing Values:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Summary Statistics:

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
# check data type
print(df.dtypes)

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
# ==========================
# Data Cleaning
# ==========================

# Remove duplicate rows (if any)
df.drop_duplicates(inplace=True)


# Fill missing values in the 'Age' column using the median value
# Median is preferred because Age may contain outliers
df["Age"] = df["Age"].fillna(df["Age"].median())

# Fill missing values in the 'Embarked' column using the most frequent value (mode)
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

# Drop the 'Cabin' column because it has too many missing values
df.drop(columns=["Cabin"], inplace=True)

In [ ]:
# Check missing values after cleaning
print("Missing Values After Cleaning:\n")
print(df.isnull().sum())

# Display the updated dataset shape
print("\nDataset Shape:", df.shape)

# Display the first 5 rows
df.head()

Missing Values After Cleaning:

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

Dataset Shape: (891, 11)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

Task 2 Machine Learning

In [ ]:
# ==========================
# Feature Selection
# ==========================

# Select input features (X)
X = df[["Pclass", "Sex", "Age", "SibSp", "Parch", "Fare", "Embarked"]]

# Select target variable (y)
y = df["Survived"]

# Display feature and target shapes
print("Features Shape:", X.shape)
print("Target Shape:", y.shape)

Features Shape: (891, 7)
Target Shape: (891,)

In [ ]:
# Import  train_test_split
from sklearn.model_selection import train_test_split

# Split the dataset into training and testing sets
# 80% Training Data
# 20% Testing Data

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state=42)

# Display dataset sizes
print("Training Samples:", X_train.shape[0])
print("Testing Samples :", X_test.shape[0])

Training Samples: 712
Testing Samples : 179

In [ ]:
# Import preprocessing tools
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline

# # Define categorical and numerical columns
categorical_cols = X_train.select_dtypes(include=['object']).columns.tolist()
# select numerical column

numerical_cols = X_train.select_dtypes(include=["int64","float64"]).columns.tolist()
print("Categorical columns:", categorical_cols)
print("Numerical columns:", numerical_cols)

Categorical columns: ['Sex', 'Embarked']
Numerical columns: ['Pclass', 'Age', 'SibSp', 'Parch', 'Fare']

In [ ]:
# ==========================
# Step 4: Create Preprocessing Pipeline
# ==========================

# Import required preprocessing tools
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

# Create a preprocessing pipeline
preprocessor = ColumnTransformer(
    transformers=[
        # Apply One-Hot Encoding to categorical columns
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols),

        # Apply StandardScaler to numerical columns
        ("num", StandardScaler(), numerical_cols)
    ]
)

# Display the preprocessing pipeline
print(preprocessor)

ColumnTransformer(transformers=[('cat', OneHotEncoder(handle_unknown='ignore'),
                                 ['Sex', 'Embarked']),
                                ('num', StandardScaler(),
                                 ['Pclass', 'Age', 'SibSp', 'Parch', 'Fare'])])

In [ ]:
# ==========================
# Step 5: Create and Train Logistic Regression Model
# ==========================

# Import Logistic Regression
from sklearn.linear_model import LogisticRegression

# Create a machine learning pipeline
# First: preprocess the data
# Second: train the Logistic Regression model
logistic_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", LogisticRegression(random_state=42, max_iter=1000))
])

# Train the pipeline using only the training data
logistic_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Sex', 'Embarked']),
                                                 ('num', StandardScaler(),
                                                  ['Pclass', 'Age', 'SibSp',
                                                   'Parch', 'Fare'])])),
                ('classifier',
                 LogisticRegression(max_iter=1000, random_state=42))])

In [ ]:
# ==========================
# Step 6: Make Predictions
# ==========================

# Predict the target values for the test dataset
y_pred = logistic_pipeline.predict(X_test)

print("Prediction completed successfully!")

Prediction completed successfully!

In [ ]:
# ==========================
# Step 7: Model Evaluation
# ==========================

# Import evaluation metrics
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

# Print evaluation metrics
print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall   :", recall_score(y_test, y_pred))
print("F1-Score :", f1_score(y_test, y_pred))

# Print confusion matrix
print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred))

# Print detailed classification report
print("\nClassification Report")
print(classification_report(y_test, y_pred))

Accuracy : 0.8100558659217877
Precision: 0.7857142857142857
Recall   : 0.7432432432432432
F1-Score : 0.7638888888888888

Confusion Matrix
[[90 15]
 [19 55]]

Classification Report
              precision    recall  f1-score   support

           0       0.83      0.86      0.84       105
           1       0.79      0.74      0.76        74

    accuracy                           0.81       179
   macro avg       0.81      0.80      0.80       179
weighted avg       0.81      0.81      0.81       179

In [ ]:
# ==========================
# Step 8: Check Class Distribution
# ==========================

# Display the number of samples in each class
print(df["Survived"].value_counts())

# Display the percentage of each class
print("\nClass Percentage:")
print(df["Survived"].value_counts(normalize=True) * 100)

Survived
0    549
1    342
Name: count, dtype: int64

Class Percentage:
Survived
0    61.616162
1    38.383838
Name: proportion, dtype: float64

In [ ]:
# ==========================
# Step 9: Train Decision Tree Classifier
# ==========================

# Import Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier

# Create a machine learning pipeline
# Step 1: Preprocess the data
# Step 2: Train the Decision Tree model
decision_tree_pipeline = Pipeline([

    # Apply preprocessing (Encoding + Scaling)
    ("preprocessor", preprocessor),

    # Create Decision Tree model
    ("classifier", DecisionTreeClassifier(random_state=42))
])

# Train the model using only the training dataset
decision_tree_pipeline.fit(X_train, y_train)

print("Decision Tree model trained successfully!")

Decision Tree model trained successfully!

In [ ]:
# ==========================
# Step 10: Make Predictions using Decision Tree
# ==========================

# Predict the target values for the test dataset
dt_y_pred = decision_tree_pipeline.predict(X_test)

print("Prediction completed successfully!")

Prediction completed successfully!

In [ ]:
# ==========================
# Step 11: Evaluate Decision Tree Model
# ==========================

# Import evaluation metrics
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

# Display Accuracy
print("Accuracy :", accuracy_score(y_test, dt_y_pred))

# Display Precision
print("Precision:", precision_score(y_test, dt_y_pred))

# Display Recall
print("Recall   :", recall_score(y_test, dt_y_pred))

# Display F1 Score
print("F1-Score :", f1_score(y_test, dt_y_pred))

# Display Confusion Matrix
print("\nConfusion Matrix")
print(confusion_matrix(y_test, dt_y_pred))

# Display Classification Report
print("\nClassification Report")
print(classification_report(y_test, dt_y_pred))

Accuracy : 0.776536312849162
Precision: 0.717948717948718
Recall   : 0.7567567567567568
F1-Score : 0.7368421052631579

Confusion Matrix
[[83 22]
 [18 56]]

Classification Report
              precision    recall  f1-score   support

           0       0.82      0.79      0.81       105
           1       0.72      0.76      0.74        74

    accuracy                           0.78       179
   macro avg       0.77      0.77      0.77       179
weighted avg       0.78      0.78      0.78       179

In [ ]:
# ==========================
# Step 12: Train Random Forest Classifier
# ==========================

# Import Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier

# Create a machine learning pipeline
# Step 1: Preprocess the data
# Step 2: Train the Random Forest model
random_forest_pipeline = Pipeline([

    # Apply preprocessing (Encoding + Scaling)
    ("preprocessor", preprocessor),

    # Create Random Forest model
    ("classifier", RandomForestClassifier(
        n_estimators=100,
        random_state=42
    ))
])

# Train the model using the training dataset
random_forest_pipeline.fit(X_train, y_train)

print("Random Forest model trained successfully!")

Random Forest model trained successfully!

In [ ]:
# ==========================
# Step 13: Make Predictions using Random Forest
# ==========================

# Predict the target values for the test dataset
rf_y_pred = random_forest_pipeline.predict(X_test)

print("Prediction completed successfully!")

Prediction completed successfully!

In [ ]:
# ==========================
# Step 14: Evaluate Random Forest Model
# ==========================

# Import evaluation metrics
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

# Display Accuracy
print("Accuracy :", accuracy_score(y_test, rf_y_pred))

# Display Precision
print("Precision:", precision_score(y_test, rf_y_pred))

# Display Recall
print("Recall   :", recall_score(y_test, rf_y_pred))

# Display F1 Score
print("F1-Score :", f1_score(y_test, rf_y_pred))

# Display Confusion Matrix
print("\nConfusion Matrix")
print(confusion_matrix(y_test, rf_y_pred))

# Display Classification Report
print("\nClassification Report")
print(classification_report(y_test, rf_y_pred))

Accuracy : 0.8100558659217877
Precision: 0.7941176470588235
Recall   : 0.7297297297297297
F1-Score : 0.7605633802816901

Confusion Matrix
[[91 14]
 [20 54]]

Classification Report
              precision    recall  f1-score   support

           0       0.82      0.87      0.84       105
           1       0.79      0.73      0.76        74

    accuracy                           0.81       179
   macro avg       0.81      0.80      0.80       179
weighted avg       0.81      0.81      0.81       179

In [ ]:
# ==========================
# Check Class Distribution
# ==========================

# Count samples in each class
print(df["Survived"].value_counts())

# Display percentage of each class
print("\nClass Percentage:")
print(df["Survived"].value_counts(normalize=True) * 100)

Survived
0    549
1    342
Name: count, dtype: int64

Class Percentage:
Survived
0    61.616162
1    38.383838
Name: proportion, dtype: float64

In [ ]:
# ==========================
# Model Comparison Table
# ==========================

import pandas as pd

# Create a comparison table for all trained models
comparison_table = pd.DataFrame({

    "Model": [
        "Logistic Regression",
        "Decision Tree",
        "Random Forest"
    ],

    "Accuracy": [
        0.8101,
        0.7765,
        0.8101
    ],

    "Precision": [
        0.7857,
        0.7179,
        0.7941
    ],

    "Recall": [
        0.7432,
        0.7568,
        0.7297
    ],

    "F1-Score": [
        0.7639,
        0.7368,
        0.7606
    ]
})

# Sort models by F1-Score (Highest First)
comparison_table = comparison_table.sort_values(by="F1-Score", ascending=False)

# Display the comparison table
print(comparison_table)

                 Model  Accuracy  Precision  Recall  F1-Score
0  Logistic Regression    0.8101     0.7857  0.7432    0.7639
2        Random Forest    0.8101     0.7941  0.7297    0.7606
1        Decision Tree    0.7765     0.7179  0.7568    0.7368

In [ ]:
# ==========================
# Step 16: Stratified K-Fold Cross-Validation
# ==========================

# Import required tools
from sklearn.model_selection import StratifiedKFold, cross_validate

# Create Stratified K-Fold cross-validation
# Stratification keeps the class distribution similar in every fold
stratified_cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

# Perform cross-validation on the complete pipeline
cv_results = cross_validate(
    logistic_pipeline,
    X,
    y,
    cv=stratified_cv,
    scoring="f1"
)

# Display F1-score for each fold
print("F1-Score for each fold:")
print(cv_results["test_score"])

# Display mean F1-score
print("\nMean F1-Score:",
      cv_results["test_score"].mean())

# Display standard deviation
print("Standard Deviation:",
      cv_results["test_score"].std())

F1-Score for each fold:
[0.70503597 0.72868217 0.704      0.71532847 0.76811594]

Mean F1-Score: 0.7242325101895855
Standard Deviation: 0.023675720164419746

In [ ]:
# ==========================
# Step 17: Hyperparameter Search
# ==========================

# Import GridSearchCV
from sklearn.model_selection import GridSearchCV

# Define hyperparameters to search
param_grid = {
    "classifier__C": [0.01, 0.1, 1, 10],
    "classifier__solver": ["liblinear", "lbfgs"]
}

# Create GridSearchCV using the complete pipeline
grid_search = GridSearchCV(
    estimator=logistic_pipeline,
    param_grid=param_grid,
    scoring="f1",
    cv=stratified_cv,
    n_jobs=-1
)

# Run the hyperparameter search on the training data
grid_search.fit(X_train, y_train)

# Display the best hyperparameter combination
print("Best Parameters:")
print(grid_search.best_params_)

# Display the best cross-validation F1-score
print("\nBest Cross-Validation F1-Score:")
print(grid_search.best_score_)

Best Parameters:
{'classifier__C': 1, 'classifier__solver': 'liblinear'}

Best Cross-Validation F1-Score:
0.7178686403154346

In [ ]:
# ==========================
# Step 18: Final Model Comparison
# ==========================

# Create a table containing the performance of all trained models
final_comparison = pd.DataFrame({
    "Rank": [1, 2, 3],
    "Model": [
        "Logistic Regression",
        "Random Forest",
        "Decision Tree"
    ],
    "Accuracy": [
        0.8100558659,
        0.8100558659,
        0.7765363128
    ],
    "Precision": [
        0.7857142857,
        0.7941176471,
        0.7179487179
    ],
    "Recall": [
        0.7432432432,
        0.7297297297,
        0.7567567568
    ],
    "F1-Score": [
        0.7638888889,
        0.7605633803,
        0.7368421053
    ]
})

# Display the final comparison table
print(final_comparison)

   Rank                Model  Accuracy  Precision    Recall  F1-Score
0     1  Logistic Regression  0.810056   0.785714  0.743243  0.763889
1     2        Random Forest  0.810056   0.794118  0.729730  0.760563
2     3        Decision Tree  0.776536   0.717949  0.756757  0.736842